## Preprocessing

In [1]:
# Importing dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score
import pandas as pd
import tensorflow as tf

# Setting random seed for replicable results
tf.random.set_seed(42)

#  Importing and reading the charity_data.csv
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [2]:
# Dropping non-beneficial ID columns
application_df = application_df.drop(columns=['EIN', 'NAME'])
application_df.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [3]:
# Determining number of unique values in each column
application_df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [4]:
# Looking at APPLICATION_TYPE value counts to identify and replace with "Other"
app_value_counts = application_df['APPLICATION_TYPE'].value_counts()
app_value_counts

APPLICATION_TYPE
T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: count, dtype: int64

In [5]:
# Choosing a cutoff value and creating a list of application types to be replaced with "Other"
application_types_to_replace = app_value_counts[app_value_counts <= 156].index.tolist()

# Replacing in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Checking replacement
application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: count, dtype: int64

In [6]:
# Looking at CLASSIFICATION value counts to identify and replace with "Other"
class_value_counts = application_df['CLASSIFICATION'].value_counts()
class_value_counts

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: count, Length: 71, dtype: int64

In [7]:
# Looking at CLASSIFICATION value counts >1
class_value_counts[class_value_counts > 1]

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: count, dtype: int64

In [8]:
# Choosing a cutoff value and creating a list of classifications to be replaced
classifications_to_replace = class_value_counts[class_value_counts <= 777].index.tolist()

# Replacing in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Checking to make sure replacement was successful
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: count, dtype: int64

In [9]:
application_df.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [10]:
# Converting categorical data to numeric
dummies_df = pd.get_dummies(application_df, dtype='float')

dummies_df.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,1,108590,1,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,1,5000,0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,1,6692,1,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,1,142590,1,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [11]:
# Splitting preprocessed data into features and target arrays
y = dummies_df['IS_SUCCESSFUL']
X = dummies_df.drop(columns=['IS_SUCCESSFUL'])

# Splitting preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, stratify=y)

In [12]:
print(y_train.shape)
print(y_test.shape)

(25724,)
(8575,)

In [13]:
print(X_train.shape)
print(X_test.shape)

(25724, 43)
(8575, 43)

In [14]:
# Creating StandardScaler instance
scaler = StandardScaler()

# Fitting StandardScaler
X_scaler = scaler.fit(X_train)

# Scaling the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Original Model

In [15]:
## Keeping original model outputs for reference

# Defining original model
number_input_features = X_train.shape[1]
input_nodes = 80
hidden_layer_nodes = 30

nn = tf.keras.models.Sequential()

# Input layer
nn.add(
    tf.keras.layers.Dense(units=input_nodes, input_dim=number_input_features, activation='relu')
)

# Hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_layer_nodes, activation='relu'))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# Checking the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 80)                3520

 dense_1 (Dense)             (None, 30)                2430

 dense_2 (Dense)             (None, 1)                 31

=================================================================
Total params: 5981 (23.36 KB)
Trainable params: 5981 (23.36 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [16]:
# Compiling the model
nn.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [17]:
# Creating callback to save model's weight every 5 epochs
checkpoints = tf.keras.callbacks.ModelCheckpoint('AlphabetSoupCharity.h5', save_weights_only=False, save_freq=5)
# Training model
fit_model = nn.fit(X_train, y_train, epochs=100, callbacks=checkpoints)

Epoch 1/100
 16/804 [..............................] - ETA: 9s - loss: 156661.5312 - accuracy: 0.4414

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(

804/804 [==============================] - 11s 11ms/step - loss: 53515.7812 - accuracy: 0.4942
Epoch 2/100
804/804 [==============================] - 5s 6ms/step - loss: 64432.8203 - accuracy: 0.4818
Epoch 3/100
804/804 [==============================] - 5s 6ms/step - loss: 32775.0117 - accuracy: 0.5021
Epoch 4/100
804/804 [==============================] - 5s 7ms/step - loss: 41952.2930 - accuracy: 0.4989
Epoch 5/100
804/804 [==============================] - 5s 6ms/step - loss: 23419.9238 - accuracy: 0.5021
Epoch 6/100
804/804 [==============================] - 5s 7ms/step - loss: 46800.6836 - accuracy: 0.5203
Epoch 7/100
804/804 [==============================] - 6s 8ms/step - loss: 12306.4082 - accuracy: 0.5206
Epoch 8/100
804/804 [==============================] - 5s 6ms/step - loss: 9443.5703 - accuracy: 0.5093
Epoch 9/100
804/804 [==============================] - 6s 7ms/step - loss: 17814.6797 - accuracy: 0.5168
Epoch 10/100
804/804 [==============================] - 4s 6ms/step - loss: 25766.4297 - accuracy: 0.5103
Epoch 11/100
804/804 [==============================] - 5s 6ms/step - loss: 24432.6270 - accuracy: 0.5030
Epoch 12/100
804/804 [==============================] - 5s 7ms/step - loss: 17668.3359 - accuracy: 0.5138
Epoch 13/100
804/804 [==============================] - 5s 6ms/step - loss: 5964.0552 - accuracy: 0.5250
Epoch 14/100
804/804 [==============================] - 6s 7ms/step - loss: 2656.6482 - accuracy: 0.5196
Epoch 15/100
804/804 [==============================] - 5s 6ms/step - loss: 4054.3450 - accuracy: 0.5506
Epoch 16/100
804/804 [==============================] - 5s 6ms/step - loss: 6275.4404 - accuracy: 0.5169
Epoch 17/100
804/804 [==============================] - 6s 7ms/step - loss: 1246.4230 - accuracy: 0.5114
Epoch 18/100
804/804 [==============================] - 5s 6ms/step - loss: 1098.5059 - accuracy: 0.5014
Epoch 19/100
804/804 [==============================] - 5s 6ms/step - loss: 1588.7522 - accuracy: 0.5014
Epoch 20/100
804/804 [==============================] - 6s 7ms/step - loss: 397.8932 - accuracy: 0.5161
Epoch 21/100
804/804 [==============================] - 5s 6ms/step - loss: 199.1750 - accuracy: 0.5314
Epoch 22/100
804/804 [==============================] - 6s 7ms/step - loss: 0.6911 - accuracy: 0.5324
Epoch 23/100
804/804 [==============================] - 5s 6ms/step - loss: 0.6911 - accuracy: 0.5324
Epoch 24/100
804/804 [==============================] - 5s 6ms/step - loss: 0.6911 - accuracy: 0.5324
Epoch 25/100
804/804 [==============================] - 6s 7ms/step - loss: 0.6911 - accuracy: 0.5324
Epoch 26/100
804/804 [==============================] - 5s 6ms/step - loss: 0.6911 - accuracy: 0.5324
Epoch 27/100
804/804 [==============================] - 5s 6ms/step - loss: 0.6911 - accuracy: 0.5324
Epoch 28/100
804/804 [==============================] - 5s 7ms/step - loss: 0.6911 - accuracy: 0.5324
Epoch 29/100
804/804 [==============================] - 5s 6ms/step - loss: 0.6911 - accuracy: 0.5324
Epoch 30/100
804/804 [==============================] - 6s 7ms/step - loss: 0.6912 - accuracy: 0.5324
Epoch 31/100
804/804 [==============================] - 5s 6ms/step - loss: 0.6911 - accuracy: 0.5324
Epoch 32/100
804/804 [==============================] - 5s 6ms/step - loss: 0.6911 - accuracy: 0.5324
Epoch 33/100
804/804 [==============================] - 6s 7ms/step - loss: 0.6911 - accuracy: 0.5324
Epoch 34/100
804/804 [==============================] - 5s 6ms/step - loss: 0.6911 - accuracy: 0.5324
Epoch 35/100
804/804 [==============================] - 5s 6ms/step - loss: 0.6911 - accuracy: 0.5324
Epoch 36/100
804/804 [==============================] - 6s 7ms/step - loss: 0.6911 - accuracy: 0.5324
Epoch 37/100
804/804 [==============================] - 5s 6ms/step - loss: 0.6912 - accuracy: 0.5324
Epoch 38/100
804/804 [==============================] - 5s 7ms/step - loss: 0.6912 - accuracy: 0.5324
Epoch 39/100
804/804 [==============================] - 5s 6ms/step - loss: 0.6911 - accuracy: 0.5324
Epoch 40/100
804/804 [==============================] - 5s 6ms/step - loss: 0.6912 - accuracy: 0.5324
Epoch 41/100
804/804 [==============================] - 6s 8ms/step - loss: 0.6912 - accuracy: 0.5324
Epoch 42/100
804/804 [==============================] - 5s 6ms/step - loss: 0.6911 - accuracy: 0.5324
Epoch 43/100
804/804 [==============================] - 5s 6ms/step - loss: 0.6912 - accuracy: 0.5324
Epoch 44/100
804/804 [==============================] - 6s 7ms/step - loss: 0.6911 - accuracy: 0.5324
Epoch 45/100
804/804 [==============================] - 5s 6ms/step - loss: 0.6911 - accuracy: 0.5324
Epoch 46/100
804/804 [==============================] - 5s 6ms/step - loss: 0.6911 - accuracy: 0.5324
Epoch 47/100
804/804 [==============================] - 5s 6ms/step - loss: 0.6911 - accuracy: 0.5324
Epoch 48/100
804/804 [==============================] - 5s 6ms/step - loss: 0.6911 - accuracy: 0.5324
Epoch 49/100
804/804 [==============================] - 6s 7ms/step - loss: 0.6910 - accuracy: 0.5324
Epoch 50/100
804/804 [==============================] - 5s 6ms/step - loss: 0.6912 - accuracy: 0.5324
Epoch 51/100
804/804 [==============================] - 5s 6ms/step - loss: 0.6911 - accuracy: 0.5324
Epoch 52/100
804/804 [==============================] - 6s 7ms/step - loss: 0.6912 - accuracy: 0.5324
Epoch 53/100
804/804 [==============================] - 5s 6ms/step - loss: 0.6912 - accuracy: 0.5324
Epoch 54/100
804/804 [==============================] - 6s 7ms/step - loss: 0.6912 - accuracy: 0.5324
Epoch 55/100
804/804 [==============================] - 5s 6ms/step - loss: 0.6912 - accuracy: 0.5324
Epoch 56/100
804/804 [==============================] - 5s 6ms/step - loss: 0.6911 - accuracy: 0.5324
Epoch 57/100
804/804 [==============================] - 6s 7ms/step - loss: 0.6912 - accuracy: 0.5324
Epoch 58/100
804/804 [==============================] - 5s 6ms/step - loss: 0.6913 - accuracy: 0.5324
Epoch 59/100
804/804 [==============================] - 5s 6ms/step - loss: 0.6913 - accuracy: 0.5324
Epoch 60/100
804/804 [==============================] - 6s 7ms/step - loss: 0.6912 - accuracy: 0.5324
Epoch 61/100
804/804 [==============================] - 5s 6ms/step - loss: 0.6912 - accuracy: 0.5324
Epoch 62/100
804/804 [==============================] - 6s 7ms/step - loss: 0.6912 - accuracy: 0.5324
Epoch 63/100
804/804 [==============================] - 5s 6ms/step - loss: 0.6912 - accuracy: 0.5324
Epoch 64/100
804/804 [==============================] - 5s 6ms/step - loss: 0.6912 - accuracy: 0.5324
Epoch 65/100
804/804 [==============================] - 6s 7ms/step - loss: 0.6912 - accuracy: 0.5324
Epoch 66/100
804/804 [==============================] - 5s 6ms/step - loss: 0.6913 - accuracy: 0.5324
Epoch 67/100
804/804 [==============================] - 5s 6ms/step - loss: 0.6911 - accuracy: 0.5301
Epoch 68/100
804/804 [==============================] - 6s 7ms/step - loss: 0.6912 - accuracy: 0.5324
Epoch 69/100
804/804 [==============================] - 5s 6ms/step - loss: 0.6912 - accuracy: 0.5324
Epoch 70/100
804/804 [==============================] - 5s 6ms/step - loss: 0.6913 - accuracy: 0.5324
Epoch 71/100
804/804 [==============================] - 5s 6ms/step - loss: 0.6912 - accuracy: 0.5324
Epoch 72/100
804/804 [==============================] - 5s 6ms/step - loss: 0.6912 - accuracy: 0.5324
Epoch 73/100
804/804 [==============================] - 6s 7ms/step - loss: 0.6913 - accuracy: 0.5324
Epoch 74/100
804/804 [==============================] - 5s 6ms/step - loss: 0.6912 - accuracy: 0.5324
Epoch 75/100
804/804 [==============================] - 5s 6ms/step - loss: 0.6911 - accuracy: 0.5324
Epoch 76/100
804/804 [==============================] - 6s 7ms/step - loss: 0.6911 - accuracy: 0.5324
Epoch 77/100
804/804 [==============================] - 5s 6ms/step - loss: 0.6912 - accuracy: 0.5324
Epoch 78/100
804/804 [==============================] - 5s 6ms/step - loss: 0.6912 - accuracy: 0.5324
Epoch 79/100
804/804 [==============================] - 5s 7ms/step - loss: 0.6912 - accuracy: 0.5324
Epoch 80/100
804/804 [==============================] - 5s 6ms/step - loss: 0.6912 - accuracy: 0.5324
Epoch 81/100
804/804 [==============================] - 6s 7ms/step - loss: 0.6913 - accuracy: 0.5299
Epoch 82/100
804/804 [==============================] - 5s 6ms/step - loss: 0.6912 - accuracy: 0.5324
Epoch 83/100
804/804 [==============================] - 5s 6ms/step - loss: 0.6913 - accuracy: 0.5324
Epoch 84/100
804/804 [==============================] - 6s 7ms/step - loss: 0.6910 - accuracy: 0.5324
Epoch 85/100
804/804 [==============================] - 5s 6ms/step - loss: 0.6912 - accuracy: 0.5324
Epoch 86/100
804/804 [==============================] - 5s 6ms/step - loss: 0.6912 - accuracy: 0.5324
Epoch 87/100
804/804 [==============================] - 6s 7ms/step - loss: 0.6913 - accuracy: 0.5324
Epoch 88/100
804/804 [==============================] - 5s 6ms/step - loss: 0.6912 - accuracy: 0.5324
Epoch 89/100
804/804 [==============================] - 5s 7ms/step - loss: 0.6912 - accuracy: 0.5324
Epoch 90/100
804/804 [==============================] - 5s 6ms/step - loss: 0.6911 - accuracy: 0.5324
Epoch 91/100
804/804 [==============================] - 5s 6ms/step - loss: 0.6912 - accuracy: 0.5324
Epoch 92/100
804/804 [==============================] - 6s 7ms/step - loss: 0.6912 - accuracy: 0.5324
Epoch 93/100
804/804 [==============================] - 5s 6ms/step - loss: 0.6912 - accuracy: 0.5324
Epoch 94/100
804/804 [==============================] - 5s 6ms/step - loss: 0.6912 - accuracy: 0.5324
Epoch 95/100
804/804 [==============================] - 6s 7ms/step - loss: 0.6911 - accuracy: 0.5324
Epoch 96/100
804/804 [==============================] - 5s 6ms/step - loss: 0.6912 - accuracy: 0.5324
Epoch 97/100
804/804 [==============================] - 5s 6ms/step - loss: 0.6912 - accuracy: 0.5324
Epoch 98/100
804/804 [==============================] - 5s 7ms/step - loss: 0.6912 - accuracy: 0.5324
Epoch 99/100
804/804 [==============================] - 5s 6ms/step - loss: 0.6912 - accuracy: 0.5324
Epoch 100/100
804/804 [==============================] - 6s 7ms/step - loss: 0.6913 - accuracy: 0.5324

In [18]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.9585 - accuracy: 0.6880 - 482ms/epoch - 2ms/step
Loss: 0.9584583640098572, Accuracy: 0.6880466341972351

In [19]:
import keras
print(tf.version.VERSION)
print(keras.__version__)

2.15.0
2.15.0

In [20]:
# Export our model to HDF5 file
nn.save('AlphabetSoupCharity.h5', save_format='h5')